app:
  name: CurrencyExchangeApp
  port: 3000

database:
  host: localhost
  port: 3306
  user: root
  password:
  name: currency_exchange_db

jwt:
  secret:
  expire_minutes: 1440

redis:
  addr: "127.0.0.1:6379"
  password:
  db: 0

like_worker:
  batch: 200
  interval_seconds: 1
